#!/bin/sh
URL=$1
ID=$2
FOLDER="$3/${ID}"
NUM=$4
PSEUDO=$5

FICHIER="impression"
IMAGE="${FOLDER}/${FICHIER}"

mkdir -p "${FOLDER}"

curl -s "${URL}/getphoto/${ID}/${NUM}" --output "${IMAGE}.jpg"

cartoon -p 30 -n 40 -e 6 -m 1 ${IMAGE}.jpg ${IMAGE}.png
convert ${IMAGE}.png -flatten -colorspace Gray -negate -edge 2 -negate -threshold 50% ${IMAGE}.ppm

# on insert le pseudo
convert -pointsize 70 -font "From-Street-Art" label:"${PSEUDO}" -threshold 50% -trim +repage -bordercolor white -border 5x5 ${FOLDER}/text.ppm
convert ${IMAGE}.ppm -gravity center ${FOLDER}/text.ppm -append ${IMAGE}_text.ppm

convert -rotate -90 ${IMAGE}_text.ppm ${IMAGE}_text_rotated.ppm
potrace -s ${IMAGE}_text_rotated.ppm -b svg --unit 100 --turdsize 5 --turnpolicy black -o ${IMAGE}.svg

curl -s -X POST  "${URL}/upload-svg/${ID}" --form "file=@${IMAGE}.svg"
