#!/bin/sh
URL=$1
ID=$2
FOLDER="$3/${ID}"
NUM=$4
PSEUDO=$5

FICHIER="impression"
IMAGE="${FOLDER}/${FICHIER}"

mkdir -p "${FOLDER}"

curl -s "${URL}/getphoto/${ID}/${NUM}" --output "${IMAGE}.jpg"


convert ${IMAGE}.jpg -noise 5 -resize 300 ${IMAGE}.pbm
# calcul du svg
python /usr/local/bin/tspart.py --max-segments=5000 --runs=1 ${IMAGE}.pbm
mv "${IMAGE}.svg" "${IMAGE}_tmp.svg"

# on insert le pseudo
convert -pointsize 70 -font "From-Street-Art" label:"${PSEUDO}" -threshold 50% -trim +repage -bordercolor white -border 5x5 "${FOLDER}/text.ppm"
potrace -s "${FOLDER}/text.ppm" -b svg --unit 100 --turdsize 5 --turnpolicy black -o "${FOLDER}/text.svg"
/usr/local/svg_stack/bin/svg_stack.py --direction=v --margin=0 "${IMAGE}_tmp.svg" ${FOLDER}/text.svg > "${IMAGE}_text.svg"

/usr/local/svg/bin/svg_rotate.py --input "${IMAGE}_text.svg" --output "${IMAGE}.svg"

curl -s -X POST  "${URL}/upload-svg/${ID}" --form "file=@${IMAGE}.svg"
